---
title: "R Notebook"
output: html_notebook
---




```{r}
bitcoin<-coin_history(coin_id ="bitshares", vs_currency = "usd",days = 5000 ,  interval = "daily")


```


```{r}
delay<-read.csv("C:/Users/Kevin Meng/OneDrive/Documents/Portfolio Management/flipper.csv",header=TRUE)
delay<-delay[,"Growth.if.One.day.delay"] 
```


```{r}

btc<-binance_klines('BTCUSDT', interval = '1d',start_time = '2013-01-01', end_time = '2023-01-22')
```


```{r}
btc<-subset(btc, select = c(open_time,close))


time<-btc[1:500,1]

data<-btc[1:500,2]

max_price<-c(rep(c(NA),times=29),max(data[1:30,]))
min_price<-c(rep(c(NA),times=29),min(data[1:30,]))

x=31
y=2
while (x<=nrow(data)) {
  
  df_max=max(data[y:x,])
  max_price = append(max_price,df_max)
  
    
  df_min=min(data[y:x,])
  min_price = append(min_price,df_min)
  
  
  y = y+1
  x = x+1
}

new<-cbind(time,data,max_price,min_price)

new$max_price=shift(new$max_price)
new$min_price=shift(new$min_price)

new$below20<-(((new$close - new$max_price))/new$max_price)*100
new$above20<-(((new$close - new$min_price))/new$min_price)*100

new<-new%>%mutate(sell_signal = ifelse(below20<= -20,-2,0))
new<-new%>%mutate(buy_signal = ifelse(above20 > 20,1,0))

new<-new%>%mutate(position = ifelse(buy_signal+sell_signal < 0,0,1))

new$benchmark_ret<-ROC(new$close,type='discrete')

new<-new%>%mutate(port_return = ifelse(position == 1,benchmark_ret,0))

new$port_return<-ifelse(is.na(new$port_return),0,new$port_return)

new$benchmark_ret<-ifelse(is.na(new$benchmark_ret),0,new$benchmark_ret)

new$invest_growth<-cumprod(1+new$port_return)
new$benchmark_growth<-cumprod(1+new$benchmark_ret)

strategy<-new%>%select(c("open_time","benchmark_growth","invest_growth"))

strategy$open_time<- as.POSIXct(strategy$open_time)
strategy<-xts(strategy[,-1], order.by= as.POSIXct(strategy$open_time))

#strategy$Growth.if.One.day.delay<-delay



colnames(strategy)<-c("Bitcoin","Bitcoin Flipper")


plot<-tidy(strategy)%>%ggplot(aes(x=index,y=value,color=series))+geom_line()+mytheme+theme(legend.position = c(0.2,0.8))+scale_color_manual(values = c("cornflowerblue","firebrick3"))+labs(title="30 Day Lookback 20% Flipper Strategy on BinanceUSDT",x="",y="Growth of 1 dollar", caption="By Emmanuel Maseruka   Data Source: CoinGecko")+geom_hline(yintercept = 1)

plot
```






























